
# Server Configuration
server:
  address: 0.0.0.0
  port: 8080

# Spring database
spring:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/sync_auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
