version: '3.9'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-service
    env_file:
      - ./mysql-env.env
    ports:
      - "3306:3306"
    volumes:
      - D:\licenta\mysql_database:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network: